---
- name: Ensure docker is installed
  import_playbook: ../../services/docker/docker.yml
  
- name: Install plex
  hosts: plex

  tasks:
  
    - name: Include variables
      include_vars: 
        dir: ../../vars
        
    - name: Mount media drive from NAS
      become: true
      ansible.posix.mount:
        src: //10.0.30.10/Media
        path: /home/josh/media
        opts: "rw,vers=3,username={{ truenas_username }},password={{ truenas_password }},uid=1000,gid=999"
        fstype: cifs
        state: mounted

    - name: Install plex
      include_role:
        name: ../../roles/ts-container
      vars:
        authkey: "{{ tailscale_containers_oauth_key['key'] }}"
        service_name: plex
        container_image: lscr.io/linuxserver/plex
        container_tag: arm64v8-latest
        https_container: true
        serve_port: 32400
        userspace_networking: "false"
        public: true
        container_volumes:
          - /home/{{ ansible_user }}/plex/config:/config
          - /home/{{ ansible_user }}/media/media:/media
        env_vars:
          PUID: "1000"
          PGID: "999"
          TZ: "America/New_York"
          Version: "docker"
        container_labels: 
          nautical-backup.enable: "true"