---
- name: Initial setup for fedora servers
  hosts: fedora
  become: true

  tasks:
    - name: Update dnf and install required system packages
      dnf:
        pkg:
          - pip
          - curl
          - nano
          - vim
          - git
          - firewalld
        state: latest
        update_cache: true

    - name: Create a new regular user with sudo privileges
      import_tasks: user.yml
      vars: 
        created_username: josh

    - name: Basic security hardening
      import_tasks: security.yml
      vars: 
        authorized_user: josh

    - name: Install and bring up tailscale
      import_tasks: ../tailscale/tailscale.yml
...