---
- name: Initial setup for fedora servers
  hosts: fedora
  become: true

  tasks:
    - name: Update dnf and install required system packages
      dnf:
        pkg:
          - pip
          - curl
          - nano
          - vim
          - git
          - firewalld
          - borgbackup
          - cifs-utils
        state: latest
        update_cache: true
    
    # - name: Include TrueNAS login info
    #   include_vars: secrets.yml
      
    # - name: Mount media drive from NAS
    #   become: true
    #   ansible.posix.mount:
    #     src: //10.0.30.10/Backups
    #     path: /home/josh/backups
    #     opts: "rw,vers=3,username={{ truenas_username }},password={{ truenas_password }},uid=1000,gid=999"
    #     fstype: cifs
    #     state: mounted

    - name: Create a new regular user with sudo privileges
      import_tasks: user.yml
      vars: 
        created_username: josh

    - name: Basic security hardening
      import_tasks: security.yml
      vars: 
        authorized_user: josh

    - name: Install and bring up tailscale
      import_tasks: ../../services/tailscale/tailscale.yml
...