---
- name: Ensure firewalld is running and enabled
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: Set default zone to 'drop'
  ansible.builtin.command: firewall-cmd --set-default-zone=drop
  register: default_zone_set
  changed_when:
    - '"ZONE_ALREADY_SET" not in default_zone_set.stderr'

- name: Allow SSH access
  ansible.builtin.firewalld:
    zone: drop
    service: ssh
    state: enabled
    permanent: yes
    immediate: yes

- name: Setup passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Set authorized key for remote user
  ansible.posix.authorized_key:
    user: "{{ authorized_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Disable SSH password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: pw_auth

- name: Disable password authentication for root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'
  register: pw_auth_root

- name: Restart SSH daemon
  service:
    name: sshd
    state: restarted
  when: pw_auth.changed or pw_auth_root.changed
...