---
- name: Install docker
  hosts: docker

# TODO - Add support for ARM64 architecture. Currently, these tasks will only work on x86 architecture.

  tasks:
  - name: Include variables
    include_vars:
      dir: ../../vars

  - name: Docker install for Ubuntu
    include_tasks: ubuntu.yml
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Docker install for Fedora
    include_tasks: fedora.yml
    when: ansible_facts['distribution'] == "Fedora"
...
