---
- name: Homelab Setup
  hosts: all

- import_playbook: baseline/proxmox/main.yml
- import_playbook: baseline/fedora/main.yml
- import_playbook: baseline/ubuntu/main.yml
# - import_playbook: services/pihole.yml
- import_playbook: services/docker.yml
# - import_playbook: containers/code-server/main.yml
# - import_playbook: containers/gitea/main.yml
# - import_playbook: containers/media/main.yml
# - import_playbook: containers/plex/main.yml
# - import_playbook: containers/paperless/main.yml
# - import_playbook: containers/plex/main.yml
# - import_playbook: containers/uptime-kuma/main.yml
# - import_playbook: containers/vikunja/main.yml
...


