---
- name: Homelab Setup
  hosts: all
  become: yes

# - import_playbook: baseline/proxmox/main.yml
- import_playbook: baseline/ubuntu/main.yml
- import_playbook: services/pihole.yml
- import_playbook: services/docker.yml
- import_playbook: services/vikunja.yml 
...


