---
- name: Install Gitea
  hosts: gitea

  tasks:
    
    - name: Include variables
      include_vars: 
        dir: ../../vars
    
    - name: Install Gitea DB
      include_role:
        name: ../../roles/ts-container
      vars:
        authkey: "{{ tailscale_containers_oauth_key['key'] }}"
        service_name: gitea-db
        container_image: postgres
        container_tag: 14
        no_serve: true
        container_volumes:
          - /home/{{ ansible_user }}/gitea-db/postgresql:/var/lib/postgresql/data
        env_vars:
          POSTGRES_PASSWORD: "{{ GITEA_DB_PASS }}"
          POSTGRES_USER: gitea
          POSTGRES_DB: gitea
        userspace_networking: "false"

    - name: Install Gitea
      include_role:
        name: ../../roles/ts-container
      vars:
        authkey: "{{ tailscale_containers_oauth_key['key'] }}"
        service_name: gitea
        container_image: gitea/gitea
        container_tag: 1.22.0-rootless
        serve_port: 3000
        container_volumes:
          - /home/{{ ansible_user }}/gitea/data:/data
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        env_vars:
          USER_UID: "1000"
          USER_GID: "999"
          GITEA__database__DB_TYPE: postgres
          GITEA__database__HOST: gitea-db.mink-pirate.ts.net:5432
          GITEA__database__NAME: gitea
          GITEA__database__USER: gitea
          GITEA__database__PASSWD: "{{ GITEA_DB_PASS }}"
        userspace_networking: "false"
...