---
- name: Ensure docker is installed
  import_playbook: ../../services/docker/main.yml
  
- name: Install Gitea
  hosts: gitea

  tasks:
    
    - name: Include variables
      include_vars: 
        dir: ../../vars

    - name: Install Gitea
      include_role:
        name: ../../roles/ts-container
      vars:
        authkey: "{{ tailscale_containers_oauth_key['key'] }}"
        service_name: gitea
        container_image: gitea/gitea
        container_tag: 1.22.0
        serve_port: 3000
        container_volumes:
          - /home/{{ ansible_user }}/gitea/data:/data
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        env_vars:
          USER_UID: "1000"
          USER_GID: "999"
          GITEA__DEFAULT__APP_NAME: "Josh Noll's Gitea"
          GITEA__mailer__ENABLED: "true" 
          GITEA__mailer__PROTOCOL: smtp
          GITEA__mailer__SMTP_PORT: "25"
          GITA__mailer__SMTP_ADDR: ntfy.mink-pirate.ts.net
          GITEA__mailer__FROM: noreply@gitea.mink-pirate.ts.net
          GITEA__mailer__ENVELOPE_FROM: noreply@gitea.mink-pirate.ts.net
        container_labels: 
          nautical-backup.enable: "true"
...