- name: Update VM inventory
  hosts: proxmox
  user: root

  tasks:

  - include_vars: ../vars/secrets.yml
  - include_vars: ../vars/machines_change_vars.yml
  - include_vars: ../vars/machines_delete_vars.yml
  
  - name: Remove desired VMs
    include_tasks: machines_delete.yml
    loop: "{{ machines_delete }}"

  - name: Make changes to desired VMs
    include_tasks: machines_change.yml
    loop: "{{ machines_change }}"