---
# TODO -- Modify to use specific version tag (rather than latest)
- name: Install and Configure Uptime Kuma
  hosts: uptime-kuma
  # user: josh
  # vars:
  #   service_name: uptime-kuma
  #   image_name: louislam/uptime-kuma
  #   image_tag: latest
  #   authkey: "{{ oauth_key['tailscale'] }}"
  #   serve_port: 3001
  
  tasks:  

    - name: Verify docker installation
      ansible.builtin.shell: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Install docker if no installation detected
      import_playbook: ../services/docker.yml
      when: not docker_installed.failed 

    - name: Install Uptime Kuma 
      include_role:
        name: ../../roles/container
      vars:
        container_name: uptime-kuma
        container_image: louislam/uptime-kuma
        container_tag: latest
        serve_port: 3001
        userspace_networking: false
        public: false
        container_volumes:
          - /home/{{ ansible_user }}/{{ container_name }}/app:/app/data
          
    # - include_role: 
    #     name: ../../roles/tailscale_sidecar

    # - name: Pull image and deploy {{ service_name }} container
    #   docker_container:
    #     name: "{{ service_name }}"
    #     image: "{{ image_name }}:{{ image_tag }}"
    #     state: started
    #     restart_policy: unless-stopped
    #     volumes: ~/{{ service_name }}/app:/app/data
    #     network_mode: container:ts-{{ service_name }}
...
