---
- name: Ensure docker is installed
  import_playbook: ../../services/docker/main.yml
  
- name: Install Uptime Kuma
  hosts: uptime_kuma

  tasks:  
    - name: Include variables
      include_vars: 
        dir: ../../vars

    - name: Install Uptime Kuma 
      include_role:
        name: ../../roles/ts-container
      vars:
        authkey: "{{ tailscale_containers_oauth_key['key'] }}"
        service_name: uptime-kuma
        container_image: louislam/uptime-kuma
        container_tag: latest
        serve_port: 3001
        userspace_networking: "false"
        public: false
        container_labels: 
          nautical-backup.enable: "true"
        container_volumes:
          - /home/{{ ansible_user }}/{{ container_name }}/app:/app/data
...
