---
- name: Include tailscale keyfile
  include_vars: ../tailscale_sidecar/vars/tailscale_oauth_key.yml
  
- name: Deploy {{ container_name }}'s tailscale sidecar container
  include_role:
    name: ../../roles/tailscale_sidecar # TODO -- Path is not relative to role folder, rather relative to where it is called from. Need to find another way to specify this path.
  vars:
    service_name: "{{ container_name }}"
    authkey: "{{ oauth_key['tailscale'] }}"
    serve_port: "{{ serve_port }}"
    userspace_networking: "{{ userspace_networking }}"
    public: "{{ public }}"

- name: Pull {{ container_name }} image and deploy container
  docker_container: 
    name: "{{ container_name }}"
    image: "{{ container_image }}:{{ container_tag }}"
    state: started
    restart_policy: unless-stopped
    volumes: "{{ container_volumes }}"
    env: "{{ env_vars }}"
    network_mode: container:ts-{{ container_name }}