---
- name: Install and Configure {{service_name}}
  hosts: "{{service_name}}"
  user: josh
  vars:
    service_name: gitea
    image_name: gitea/gitea
    image_tag: latest

  tasks:
    
    - name: Verify docker installation
      ansible.builtin.shell: docker --version
      register: docker_installed
      ignore_errors: true
    
    - block:
      - name: Pull image and deploy {{ service_name }} container
        docker_container:
          name: "{{ service_name }}"
          image: "{{ image_name }}:{{ image_tag }}"
          state: started
          restart_policy: unless-stopped
          volumes: 
            - ~/{{ service_name }}/data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
          published_ports:
            - "3000:3000"
            - "222:22"
          env:
            PUID: "1000"
            PGID: "999"

      - name: Open firewall ports
        become: yes
        ufw:
          state: enabled
          rule: allow
          port: "{{ item }}"
          proto: any
        loop:
          - "3000"
          - "222"

      when: not docker_installed.failed 
...