---
# TODO -- Modify to use specific version tag (rather than latest)
- name: Install and Configure {{ service_name }}
  hosts: uptimekuma
  user: josh
  vars:
    service_name: uptime-kuma
    image_name: louislam/uptime-kuma
    image_tag: latest

  tasks:
    
    - name: Verify docker installation
      ansible.builtin.shell: docker --version
      register: docker_installed
      ignore_errors: true
    
    - block:
      - name: Pull image and deploy {{ service_name }} container
        docker_container:
          name: "{{ service_name }}"
          image: "{{ image_name }}:{{ image_tag }}"
          state: started
          restart_policy: unless-stopped
          volumes: ~/{{ service_name }}/app:/app/data
          published_ports:
            - "3001:3001"  # <Host Port>:<Container Port>

      - name: Open firewall ports
        become: yes
        ufw:
          state: enabled
          rule: allow
          port: "3001"
          proto: any
      when: not docker_installed.failed 
...
