---
- name: Initial setup for ubuntu servers
  hosts: ubuntu
  become: true

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Update apt and install required system packages
      apt:
        pkg:
          - curl
          - nano
          - vim
          - git
          - ufw
          - neofetch
        state: latest
        update_cache: true

    - name: Create a new regular user with sudo privileges
      import_tasks: user.yml
      vars: 
        created_username: josh

    - name: Basic security hardening
      import_tasks: security.yml
      vars: 
        authorized_user: josh

    - name: Install and bring up tailscale
      import_tasks: ../tailscale/tailscale.yml
...