---
- name: Initial setup for ubuntu servers
  hosts: all
  become: true

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Create a new regular user with sudo privileges
      import_tasks: user.yml
      vars: 
        created_username: josh

    - name: Basic security hardening
      import_tasks: security.yml
      vars: 
        authorized_user: josh

    - name: Install desired packages
      import_tasks: packages.yml

    - name: Configure firewall
      import_tasks: firewall.yml

    - name: Install and bring up tailscale
      import_tasks: tailscale.yml
...