---
- name: Deploy desired VMs on Proxmox cluster
  hosts: proxmox_api
  user: root
  
  tasks:
    
    - name: Import variables
      include_vars:
        dir: vars

    - name: Create VMs from machines_deploy_vars.yml
      community.general.proxmox_kvm:
        # Credentials and api host to work from
        api_user: "{{ proxmox_username }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_host: "{{ ansible_facts['vmbr0.7']['ipv4']['address'] }}"

        # Basic VM info
        node: "{{ item.node }}" # Node the VM will be created on
        vmid: "{{ item.vmid }}"
        name: "{{ item.name }}"
        ostype: "{{ item.ostype }}" # See https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_kvm_module.html
        
        # Hardware info
        memory: "{{ item.memory }}"
        cores: "{{ item.cores }}"
        scsihw: virtio-scsi-pci
        ide:
          ide2: '{{ item.storage }}:cloudinit,format=qcow2'
        serial: 
          serial0: socket
        vga: serial0
        boot: order=scsi0;ide2
        
        ## TODO - Find a way to specify number of interfaces in vars
        # Storage and network info
        net:
          net0: 'virtio,bridge=vmbr0,tag={{ item.vlan }}'
        ipconfig:
          ipconfig0: 'ip={{ item.ip_address }},gw={{ item.gateway }}'
        nameservers: "{{ item.nameservers }}"
        
        # Cloud-init info
        ciuser: "{{ ciuser }}"
        cipassword: "{{ cipassword }}"
        sshkeys: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
        
        # Desired state
        state: present

      # Loop through desired machines in machines_deploy_vars.yml
      loop: "{{ vms_to_create }}"
          
    - name: Bootstrap VMs by importing cloud-init disk, resizing and powering VMs on
      include_tasks: bootstrap.yml
      loop: "{{ vms_to_create }}"
...