---
- name: Initial setup for proxmox servers
  hosts: proxmox_hosts
  user: root
  become: true

  tasks:

    - name: Import variables
      include_vars:
        dir: vars

    - name: Update apt and install required system packages
      apt:
        pkg:
          - aptitude
          - curl
          - nano
          - vim
          - git
          - python3-proxmoxer
          - python3-requests
        state: latest
        update_cache: true

    - name: Basic security hardening
      import_tasks: security.yml

    - name: Install and bring up tailscale
      import_tasks: ../tailscale/tailscale.yml
    
    - name: Ensure template VMs exist
      include_tasks: deploy_template.yml
  
- name: Create desired VMs
  import_playbook: create_vms.yml
...